### ISSUE TITLE
Doesn't work with v2

### ISSUE THREAD

**Issue by matteodem** [monterail/vue-multiselect#181]
I'm getting following error when trying to use vue-multiselect in a vuejs 2.0 project.

```
Uncaught TypeError: e._v is not a function
    at Proxy.render (eval at <anonymous> (bundle.js?v2.0.5:3854), <anonymous>:1:16551)
    at VueComponent.Vue._render (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:2238:22)
    at VueComponent.eval (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:1693:21)
    at Watcher.get (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:736:27)
    at new Watcher (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:728:12)
    at VueComponent.Vue._mount (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:1692:19)
    at VueComponent.Vue$2.$mount (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:5592:15)
    at init (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:1976:11)
    at createElm (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:3825:56)
    at createChildren (eval at <anonymous> (bundle.js?v2.0.5:608), <anonymous>:3871:40)
```

Also it's not possible to import `vue-multiselect/lib` because the `index.js` requires files that are not existant (for example `'./Multiselect'`).

Tested with version: `2.0.0-beta.13`

**Comment by jaybeecave** [comment]
Same problem here.

**Comment by mghignet** [comment]
Hello,

Just faced the same issue but after upgrading vue from 2.1.3 to 2.1.8 everything works fine.
For other issues, see this thread: https://github.com/monterail/vue-multiselect/issues/63

**Comment by shentao** [comment]
Updating to 2.1.8 should resolve the problem. :)

**Comment by matteodem** [comment]
Worked, thanks!

**Comment by sullyfischer** [comment]
thanks @mghignet and @shentao, it worked like a charm :)

**Comment by jaketoolson** [comment]
Same here. spent forever debugging lol.
